version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  myapp:
    image: myapp-image
    volumes:
      - ./SQL:/app/SQL
    depends_on:
      - pgadmin
