SELECT p.ID, EXTRACT(MONTH FROM DATEDIFF('MONTH', p.START_DATE, p.FINISH_DATE)) AS MONTH_COUNT
FROM project p
WHERE EXTRACT(MONTH FROM DATEDIFF('MONTH', p.START_DATE, p.FINISH_DATE)) = (
    SELECT MAX(EXTRACT(MONTH FROM DATEDIFF('MONTH', START_DATE, FINISH_DATE)))
    FROM project
    );
